### ISSUE TITLE
Player Date of Birth's possible?

### ISSUE THREAD

**Issue by zag2me** [ewenme/footy-transfer-data#4]
This is quite an amazing resource that I would like to use to fill a sports database i run (www.thesportsdb.com). We are trying to create an entire history of all sports.

Is it possible to scrape the players date of birth at all and insert into the CSV? It would really help me write some import scripts. Position and country would be even more awesome ;)

Thanks again for your work on this.

**Comment by zag2me** [comment]
I had a quick look myself as the R code is lovely and readable! Looks like the Transfermarkt page does include the DOB but only as a micromodal javascript popup on hovering over the players name. I'm guessing this means its unscrapable.

**Comment by ewenme** [comment]
you may be interested in [github.com/ewenme/squads](https://github.com/ewenme/squads)
